# Numpy

In [1]:
! pip install numpy

In [2]:
import numpy as np

arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:

arr=np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


## Creating a 1D NumPy array


In [10]:
import numpy as np

# Create a 1D array (list of numbers)
arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


## Creating a 2D NumPy array

In [13]:
# Create a 2D array (matrix of numbers)
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix)



[[1 2 3]
 [4 5 6]]


## Creating a 3D NumPy array

In [14]:
arr=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Creating a 4D NumPy array

In [15]:

arr=np.array([[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]])
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


## Creating a 5D NumPy array

In [16]:

arr=np.array([[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]],[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]]])
print(arr)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]



 [[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]


## Creating an array with random values

In [6]:

#create an array with random value
a = np.random.random((4,8))
print(a)

[[0.63435698 0.09350799 0.93420727 0.78928454 0.04401474 0.7007759
  0.4625732  0.04163713]
 [0.24825078 0.31004195 0.6474789  0.11336891 0.32431024 0.84521196
  0.61240511 0.19969126]
 [0.74827531 0.07050314 0.49313613 0.09023778 0.23832666 0.35853506
  0.98822206 0.28237875]
 [0.31810759 0.46825812 0.73752101 0.30408527 0.25852099 0.38370822
  0.31742331 0.17296597]]


## Creating an array of ones

In [18]:

ones_array = np.ones(4)

print(ones_array)


[1. 1. 1. 1.]


# Intial Placeholders
In NumPy, initial placeholders are arrays filled with default values, such as zeros, ones, or empty values, which are useful when you want to create arrays to fill later

## Array of Zeros (np.zeros)


Creates an array of all zeros.

In [20]:
import numpy as np

# 1D array of zeros with 5 elements
zeros_array = np.zeros(5)

# 2D array of zeros (3x3 matrix)
zeros_matrix = np.zeros((3, 3))

print(zeros_array)
print(zeros_matrix)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Array Filled with a Specific Value (np.full)


Creates an array filled with a specific value.

In [21]:
# 1D array of 5 elements, all set to 7
full_array = np.full(5, 7)

# 2D array (3x3 matrix) with all elements set to 9
full_matrix = np.full((3, 3), 9)

print(full_array)
print(full_matrix)


[7 7 7 7 7]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


## Array with Uninitialized Values (np.empty)


Creates an uninitialized array (faster, but contents are random).

In [22]:
# 1D array with 5 elements (values are uninitialized)
empty_array = np.empty(5)

# 2D array (2x2 matrix) with uninitialized values
empty_matrix = np.empty((2, 2))

print(empty_array)
print(empty_matrix)


[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]]


## Array of Ones (np.ones)


 Creates an array of all ones.

In [23]:
# 1D array of ones with 4 elements
ones_array = np.ones(4)

# 2D array of ones (3x2 matrix)
ones_matrix = np.ones((3, 2))

print(ones_array)
print(ones_matrix)


[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


# Slicing in Numpy

- In NumPy, slicing is used to access specific parts of arrays (subarrays) using indices. It allows you to select elements, rows, columns, or portions of arrays based on your needs

- Slicing is a powerful feature that allows efficient access and manipulation of array elements.

## 1D Array Slicing

Selects portions of a 1D array.


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Slicing from index 1 to 4 (exclusive)
slice1 = arr[1:4]

# Slicing with step size of 2
slice2 = arr[::2]

print(slice1)  
print(slice2)  


[20 30 40]
[10 30 50]


## 2D Array Slicing
Selects rows and columns from 2D arrays.

In [2]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Slice first two rows and all columns
slice1 = matrix[:2, :]

# Slice all rows and first two columns
slice2 = matrix[:, :2]

# Slice second row, second and third columns
slice3 = matrix[1, 1:3]

print(slice1)
print(slice2)
print(slice3)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[5 6]


## Negative Indexing

Negative indexing allows you to slice arrays from the end.

In [3]:
arr = np.array([10, 20, 30, 40, 50])

# Slicing last three elements
slice1 = arr[-3:]

print(slice1)  # Output: [30 40 50]


[30 40 50]


## Slicing with Steps

Skips elements or reverses arrays.

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing with a step of 2 (every second element)
slice1 = arr[::2]

# Reverse the array
reverse_slice = arr[::-1]

print(slice1)         # Output: [1 3 5 7 9]
print(reverse_slice)  # Output: [9 8 7 6 5 4 3 2 1]


[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


## Numpy Datatypes

NumPy supports a variety of data types (called dtypes) for its arrays, allowing efficient storage and manipulation of data.

## 1. Integer Types (Whole numbers)

In [1]:
import numpy as np

int_array = np.array([1, 2, 3], dtype=np.int8)
print(int_array, int_array.dtype)


[1 2 3] int8


## 2. Float Types (Decimal numbers)


In [2]:
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float32)
print(float_array, float_array.dtype)


[1.1 2.2 3.3] float32


## 3. Complex Types (Numbers with real and imaginary parts)

In [4]:
complex_array = np.array([1+2j, 3+4j], dtype=np.complex64)
print(complex_array, complex_array.dtype)


[1.+2.j 3.+4.j] complex64


## 4. Boolean Type (True/False values)

In [5]:
bool_array = np.array([True, False, True], dtype=np.bool_)
print(bool_array, bool_array.dtype)


[ True False  True] bool


## 5. String Type (Text)

In [7]:
str_array = np.array(['apple', 'banana', 'cherry'], dtype=np.str_)
print(str_array, str_array.dtype)


['apple' 'banana' 'cherry'] <U6


##### Other examples

In [8]:
arr=np.array([10,11,12,13],dtype='i8')
print(arr)
print(arr.dtype)
     

[10 11 12 13]
int64


In [9]:

arr=np.array([2.1,5.3,5.7])
newarr=arr.astype('i')
print(arr)
print(newarr)

[2.1 5.3 5.7]
[2 5 5]
